Update Jenkinsfile

diff --git a/fullstack-devops-project/Jenkinsfile b/fullstack-devops-project/Jenkinsfile
--- a/fullstack-devops-project/Jenkinsfile
+++ b/fullstack-devops-project/Jenkinsfile
@@ -53,7 +53,7 @@ pipeline {
         stage('Verify Deployment') {
             steps {
                 echo '⏳ Waiting for services to initialize...'
-                sh 'sleep 20'
+                sh 'sleep 40'
 
                 echo '📦 Running containers:'
                 sh 'docker ps'
@@ -61,17 +61,20 @@ pipeline {
                 echo '🩺 Performing backend health check...'
 
                 sh '''
-                    for i in {1..10}; do
-                        if curl -f http://$SERVER_IP:5000/api/health; then
-                            echo "✅ Backend is healthy!"
-                            exit 0
-                        fi
-                        echo "⌛ Attempt $i/10 failed. Retrying in 5 seconds..."
-                        sleep 5
-                    done
+                i=1
+                while [ $i -le 10 ]
+                do
+                    if curl -f http://localhost:5000/api/health; then
+                        echo "✅ Backend is healthy!"
+                        exit 0
+                    fi
+                    echo "⌛ Attempt $i/10 failed. Retrying in 5 seconds..."
+                    sleep 5
+                    i=$((i+1))
+                done
 
-                    echo "❌ Backend health check FAILED after multiple attempts."
-                    exit 1
+                echo "❌ Backend health check FAILED after multiple attempts."
+                exit 1
                 '''
             }
         }
