Update Jenkinsfile

diff --git a/fullstack-devops-project/Jenkinsfile b/fullstack-devops-project/Jenkinsfile
--- a/fullstack-devops-project/Jenkinsfile
+++ b/fullstack-devops-project/Jenkinsfile
@@ -36,7 +36,7 @@ pipeline {
             steps {
                 echo '🛑 Stopping old containers (if any)...'
                 dir("${PROJECT_DIR}") {
-                    sh 'docker-compose down --remove-orphans || true'
+                    sh 'docker-compose down || true'
                 }
             }
         }
@@ -52,38 +52,26 @@ pipeline {
 
         stage('Verify Deployment') {
             steps {
-
                 echo '⏳ Waiting for services to initialize...'
-                sh 'sleep 40'
+                sh 'sleep 20'
 
                 echo '📦 Running containers:'
                 sh 'docker ps'
 
-                echo '🩺 Performing frontend health check...'
-                sh '''
-                for i in {1..10}; do
-                    if curl -f http://localhost; then
-                        echo "✅ Frontend is healthy!"
-                        break
-                    fi
-                    echo "⌛ Attempt $i/10 failed. Retrying in 5 seconds..."
-                    sleep 5
-                done
-                '''
-
                 echo '🩺 Performing backend health check...'
-                sh '''
-                for i in {1..15}; do
-                    if curl -f http://localhost:5000/api/health; then
-                        echo "✅ Backend is healthy!"
-                        exit 0
-                    fi
-                    echo "⌛ Attempt $i/15 failed. Retrying in 5 seconds..."
-                    sleep 5
-                done
 
-                echo "❌ Backend health check FAILED after multiple attempts."
-                exit 1
+                sh '''
+                    for i in {1..10}; do
+                        if curl -f http://$SERVER_IP:5000/api/health; then
+                            echo "✅ Backend is healthy!"
+                            exit 0
+                        fi
+                        echo "⌛ Attempt $i/10 failed. Retrying in 5 seconds..."
+                        sleep 5
+                    done
+
+                    echo "❌ Backend health check FAILED after multiple attempts."
+                    exit 1
                 '''
             }
         }
@@ -105,14 +93,13 @@ pipeline {
         failure {
             echo '❌ Deployment failed! Displaying container logs...'
             dir("${PROJECT_DIR}") {
-                sh 'docker-compose logs frontend || true'
-                sh 'docker-compose logs backend || true'
+                sh 'docker-compose logs || true'
             }
         }
 
         always {
             echo '🧹 Cleaning unused Docker resources...'
-            sh 'docker system prune -af || true'
+            sh 'docker system prune -f || true'
         }
     }
 }
